Sites/catalog/config/routes.rb
Rails.application.routes.draw do
	resources :archives, :only => [:index, :create, :edit, :destroy, :update] do
		collection do
			get 'category_list'
			get 'tree'
			get 'toggle_testing'
		end
	end

	resources :federations
	resources :genres
	resources :disciplines
	resources :white_lists

	post '/corrections' => 'corrections#create'

	resources :exhibits, :only => [:index, :create, :destroy] do
		collection do
			get 'test_create_good'
			get 'test_create_bad'
			get 'test_destroy_good'
			get 'test_destroy_bad'
		end
	end

	resources :locals, :only => [:index, :create, :destroy, :update ] do
		collection do
			get 'test_search_good'
			get 'test_search_bad'
		end
	end

	devise_for :users

	get "home/index"

   resources :pages, :only => [:index]

	resources :search, :only => [:index] do
		collection do
			get 'autocomplete'
			get 'names'
			get 'totals'
			get 'details'
      get 'languages'
      get 'modify'
		end
	end

	resources :test_sort, :only => [:index]

	get "/test_exception_notifier" => "home#test_exception_notifier"

  put "/documents/tw/enable" => "documents#typewright_enable"
  put "/documents/tw/disable" => "documents#typewright_disable"

  get "/documents/title" => "documents#title"

  root :to => "home#index"
	post "/" => "home#index"

end

Sites/catalog/app/models/archive.rb
class Archive < ActiveRecord::Base
	has_attached_file :carousel_image,
                    :styles => { :normal => '300x300' },
                    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
                    :url => "/system/:attachment/:id/:style/:filename"
                    # to create a cropped image, use :thumb=> "100x100#".
	validates_attachment_size :carousel_image, :less_than => 5.megabytes,  :unless => Proc.new {|m| m[:thumbnail].nil?}
	validates_attachment_content_type :carousel_image, :content_type => ['image/jpeg', 'image/png', 'image/gif'], :unless => Proc.new {|m| m[:thumbnail].nil?}
  has_and_belongs_to_many :carousels
  attr_accessor :carousel_list

	def self.get_tree()
		nodes = Archive.where(typ: 'node')
		nodes = nodes.map {|node|
			{ :id => node.id, :parent_id => node.parent_id, :name => node.name, :carousel_include => node.carousel_include, :carousel_description => node.carousel_description, :children => [], :sites => [] }
		}
		root = { :id => 0, :name => 'root', :children => [], :sites => []}

		nodes.each { |node|
			if node[:parent_id] == 0
				root[:children].push(node)
			else
				nodes.each { |node2|
					if node[:parent_id] == node2[:id]
						node2[:children].push(node)
						break
					end
				}
			end
		}

		archives = Archive.where(typ: 'archive')
		archives.each { |archive|
			if archive[:parent_id] == root[:id]
				root[:sites].push(archive)
			else
				nodes.each { |node2|
					if archive[:parent_id] == node2[:id]
						node2[:sites].push(archive)
						break
					end
				}
			end
		}

		return root
	end

	def self.compare_to_solr(solr)
		actual = solr.get_archive_list()
		archives = Archive.where(typ: 'archive')
		archives = archives.map { |archive| archive['handle'] }
		extra = (actual | archives) - actual
		extra = extra.map {|site| { :handle => site, :name => Archive.find_by({ handle: site }).name, :id => Archive.find_by({ handle: site }).id } }
		return { :missing => (actual | archives) - archives, :extra => extra }
	end

	def self.get_inaccessible_sites()
		inaccessible_sites = []
		nodes = Archive.where(typ: 'node')
		archives = Archive.where(typ: 'archive')
		archives.each { |node|
			archive = node
			while node.parent_id != 0 # parent id of 0 is accessible
				node = nodes.select {|n| n[:id] == node.parent_id }
				node = node[0] if node.length > 0
				if node == []
					inaccessible_sites.push(archive)
					break
				elsif node.parent_id != 0
					node = nodes.select {|n| n[:id] == node.parent_id }
					node = node[0] if node.length > 0
					if node == []
						inaccessible_sites.push(archive)
						break
					end
				end
			end
		}
		return inaccessible_sites
	end

	def self.get_category_list
		nodes = Archive.where(typ: 'node')
		nodes = nodes.sort { |a, b| a['name'] <=> b['name'] }
		nodes = nodes.map { |node| {:name => node['name'], :value => node['id']} }
		nodes.unshift({:name => "[root]", :value => 0})
		return nodes
  end

end

Sites/catalog/app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
   before_action :set_archive, only: [:show, :update, :destroy]

   #	before_filter :must_be_logged_in
   before_filter :must_be_logged_in, :except => [:index]

   def facets
      session[:use_testing_index] ||= false
      @sites_forest = Archive.get_tree()
      is_test = Rails.env == 'test' ? :test : :live
      is_test = :shards if session[:use_testing_index] == true
      solr = Solr.factory_create(is_test)
      comp = Archive.compare_to_solr(solr)
      @missing_in_db = comp[:missing]
      @extra_in_db = comp[:extra]
      @inaccessible_sites = Archive.get_inaccessible_sites()
   end

   def category_list()
      nodes = Archive.get_category_list()
      render :json => nodes
   end

   def tree
      session[:resource_toggle] ||= {}
      expanded = params[:expanded]
      id = params[:id]
      if expanded == 'true' && id != nil
         session[:resource_toggle][id] = 'open'
      end
      if expanded == 'false' && id != nil
         session[:resource_toggle][id] = 'close'
      end
      render :text => ''	# this is just to keep from getting an error.
   end

   def toggle_testing
      session[:use_testing_index] = !session[:use_testing_index]
      redraw()
   end

   # GET /archives
   # GET /archives.json
   # GET /archives.xml
   def index
      respond_to do |format|
         format.html {
            facets()
         }
         format.json { render json: { archives: Archive.all }}
         format.xml {
            @archives = Archive.all
         }
      end
   end

   def redraw
      facets()
      render :partial => 'edit_site_list', :locals => { :sites_forest => @sites_forest, :missing_in_db => @missing_in_db, :extra_in_db => @extra_in_db, :parent_div => 'edit_site_list', :inaccessible_sites => @inaccessible_sites }
   end

   # GET /archives/1/edit
   def edit
      if params[:id].to_i != 0
         @archive = Archive.find(params[:id])
         item = @archive.attributes
         if @archive.carousel_image_file_name
            item[:carousel_image] = @archive.carousel_image.url(:normal)
         end
         if not @archive.carousels.empty?
            item[:carousel_list] = {}
            @archive.carousels.each{ |c|
               item[:carousel_list][c.id] = 1
            }
         end
         render :json => {:item => item,
                       :categories => Archive.get_category_list(),
                       :all_carousels => Carousel.all}
      else
         render :json => {:item => { :handle => params[:id] }, :categories => Archive.get_category_list()}
      end
   end

   # POST /archives
   # POST /archives.json
   # POST /archives.xml
   def create
      @archive = Archive.new(archive_params)

      respond_to do |format|
         if @archive.save
            format.html { redraw() }
            format.json { render :show, status: :created, location: @archive }
            format.xml { render :xml => @archive, :status => :created, :location => @archive }
         else
            format.html { render :action => "new" }
            format.json { render json: @archive.errors, status: :unprocessable_entity }
            format.xml { render :xml => @archive.errors, :status => :unprocessable_entity }
         end
      end
   end

   # PATCH/PUT /archives/1
   # PATCH/PUT /archives/1.json
   # PATCH/PUT /archives/1.xml
   def update
      @archive = Archive.find(params[:id])
      if params[:file]
         src = ""
         if params[:file] == 'upload'
            @archive.carousel_image = params[:archive][:carousel_image]
            @archive.save
            if @archive.errors && @archive.errors.count > 0
               err = ""
               @archive.errors.each { |key,val| err += "#{key}: #{val}"}
               render :text => "ERROR;#{err}"
            else
               src = @archive.carousel_image.url(:normal)
               render :text => "OK;#{src}"
            end
         elsif params[:file] == 'remove'
            @archive.carousel_image = nil
            @archive.save
            render :text => "OK"
         end
      else
      #params[:archive][:carousel_include] = 1 if params[:archive][:carousel_include] == 'true'

         respond_to do |format|
            if @archive.update(archive_params)
               if params[:archive][:carousel_list]
                  @archive.carousels.delete_all
                  params[:archive][:carousel_list].to_hash().each { |key, value|
                     if value.downcase == 'true'
                        @archive.carousels << Carousel.find(key)
                     end
                  }
               end
               format.html { redraw() }
               format.json { render :show, status: :ok, location: @archive }
               format.xml { head :ok }
            else
               format.html { redraw() }
               format.json { render json: @archive.errors, status: :unprocessable_entity }
               format.xml { render :xml => @archive.errors, :status => :unprocessable_entity }
            end
         end
      end

   end

   # DELETE /archives/1
   # DELETE /archives/1.json
   # DELETE /archives/1.xml
   def destroy
      @archive.destroy
      respond_to do |format|
         format.html { redraw() }
         format.json { head :no_content }
         format.xml  { head :ok }
      end
   end

   private

   # Use callbacks to share common setup or constraints between actions.
   def set_archive
      @archive = Archive.find(params[:id])
   end

   # Never trust parameters from the scary internet, only allow the white list
   # through.
   def archive_params
      params.require(:archive).permit(:carousel_description, :typ, :name, :parent_id, :handle, :site_url, :thumbnail, :carousel_list)
   end
end

Sites/catalog/app/helpers/archives_helper.rb
module ArchivesHelper
	def node_toggle(id, up)
		return raw(content_tag(:div, '', { :class => "expander#{ ' contracter' if !up}", 'data-target' => "site_#{id}", 'data-notice-url' => "/archives/tree?id=#{id}" }))
	end

	def site_links(id, name, is_node, no_edit = false)
		return "" if id == 0 || !user_signed_in?
		edit = no_edit ? '' : content_tag(:a, "[edit]", { :href => '#', :class => 'dialog',
			'data-dlg-url' => "/archives/#{id}",
			'data-dlg-method' => 'PUT',
			'data-dlg-type' => is_node ? 'editCategory' : 'editArchive',
			'data-ajax-url' => "/archives/#{id}/edit",
			'data-parent-div' => 'edit_site_list'
			})
		return edit +
			raw("&nbsp;") +
			content_tag(:a, "[delete]", { :href => '#', :class => 'dialog',
				'data-dlg-url' => "/archives/#{id}",
				'data-dlg-method' => 'DELETE',
				'data-dlg-confirm' => "Are you sure you want to delete '#{name}'?",
				'data-dlg-confirm-title' => "Confirm Deletion",
				'data-dlg-confirm-no' => 'Cancel',
				'data-parent-div' => 'edit_site_list'
			})
	end

	def format_node(node, indent, children_hidden)
		return content_tag(:div, { :class => 'row' }) do
			content_tag(:div, raw("#{raw(node_toggle(node[:id], children_hidden))}#{node[:name]}"), { :class=> "left indent#{indent}" }) +
				content_tag(:div, "#{node[:carousel_include] == 1 ? 'Yes' : ''}", { :class => 'middle' }) +
				content_tag(:div, raw(site_links(node[:id], node[:name], true)), { :class => 'right' })
		end
	end

	def format_site(site, indent)
    if site.carousels.exists?
      carousel_names = site.carousels.collect{|c| c.name}.compact.join(', ');
    end
		return content_tag(:div, { :class => 'row' }) do
			content_tag(:div, "#{site[:name]} [#{site[:handle]}]", { :class=> "left indent#{indent}" }) +
				content_tag(:div, "#{site.carousels.exists? ? carousel_names : ' '}", { :class => 'middle' }) +
				content_tag(:div, raw(site_links(site[:id], site[:name], false)), { :class => 'right' })
		end
	end
end

Sites/catalog/app/views/archives/_edit_site_list.html.erb
<% # 
    # ------------------------------------------------------------------------
    # Copyright 2009 Applied Research in Patacriticism and the University of Virginia
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #    http://www.apache.org/licenses/LICENSE-2.0
  
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # ---------------------------------------------------------------------------- -%>
<%# edit_site_list params: array sites_forest, array missing_in_db, array extra_in_db, string parent_div, array inaccessible_sites -%>
<% switch_label = session[:use_testing_index] ? "Switch to production index" : "Switch to testing index" %>
<%= link_to( switch_label, '#', { class: 'dialog', 'data-dlg-url' => "/archives/toggle_testing", 'data-parent-div' => 'edit_site_list' }) if user_signed_in? %>
<div class="header">Edit Sites and Categories</div>
<div class="site_list">
<div class="header">
	<div class="left">Resource</div>
	<div class="middle">In carousel?</div>
	<div class='right'></div>
</div>
<%= render :partial => 'facet_tree_one_branch', :locals => { :branch => sites_forest, :indent => 0, :parent_id => '', :start_hidden => false } %>
<%= link_to "[Add Category]", '#', { :class => 'dialog',
			'data-dlg-url' => "/archives",
			'data-dlg-method' => 'POST',
			'data-dlg-type' => 'addCategory',
			'data-parent-div' => 'edit_site_list',
			'data-ajax-url' => '/archives/category_list'} if user_signed_in? %>
</div>

<% if user_signed_in? %>
<div class="header">Sites not in the resource tree:</div>
<table class="limit_to">
<% for resource in missing_in_db -%>
	<tr><td class='limit_to_lvl1'><%= resource %></td><td>
		<%= link_to "[add]", '#', { :class => 'dialog',
					'data-dlg-url' => "/archives",
					'data-dlg-method' => 'POST',
					'data-dlg-type' => 'addArchive',
					'data-parent-div' => 'edit_site_list',
					'data-ajax-url' => "/archives/#{resource}/edit" } %>
	</td></tr>
<% end -%>
</table>

<div class="header">Sites not in Solr:</div>
<% missing = extra_in_db -%>
<table class="limit_to">
	<% for site in missing -%>
		<tr><td class='limit_to_lvl1'><%= site[:name] %> [<%= site[:handle] %>]</td><td><%= raw(site_links(site[:id], site[:name], true, true)) %></td></tr>
	<% end -%>
</table>

<div class="header">Inaccessible Sites:</div>
<table class="limit_to">
	<% for site in inaccessible_sites -%>
		<% sanitized_value = site['handle'].gsub("'") { |apos| "&apos;" } -%>
		<tr><td class='limit_to_lvl1'><%= site.name %> [<%= site.handle %>]</td><td><%= raw(site_links(site['id'], site['name'], true)) %></td></tr>
	<% end -%>
</table>
<% end %>

Sites/catalog/app/views/archives/_facet_tree_one_branch.html.erb
<% #
# ------------------------------------------------------------------------
#    Copyright 2009 Applied Research in Patacriticism and the University of Virginia
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#---------------------------------------------------------------------------- -%>
<%# /common/facet_tree_one_branch params: tree_node node, int indent, string parent_id, bool start_hidden -%>
<%= format_node(branch, indent, start_hidden) %>
<div id="site_<%= "#{branch[:id]}"%>" class="<%= "hidden" if start_hidden %>">
<% for child in branch[:children] -%>
	<% hidden = session[:resource_toggle] ? (session[:resource_toggle]["#{child[:id]}"] == 'open' ? false : true) : true  -%>
	<%#= site_selector(site, indent, true, parent_id, start_hidden, true, hidden, site_count ) %>
	<%= render :partial => 'facet_tree_one_branch', :locals => { :branch => child, :indent => indent + 1, :parent_id => "child_of_#{child[:id]}", :start_hidden => hidden || start_hidden } %>
<% end # each node -%>
<% for site in branch[:sites] -%>
	<%= format_site(site, indent+1) %>
	<%#= site_selector(site, indent, false, parent_id, start_hidden, site['found'], false ) %>
<% end # each site -%>
</div>

Sites/catalog/app/views/archives/index.html.erb
<%# ------------------------------------------------------------------------
    Copyright 2007 Applied Research in Patacriticism and the University of Virginia
    
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
  
        http://www.apache.org/licenses/LICENSE-2.0
  
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
---------------------------------------------------------------------------- %>
<%= make_home_path %>

<div class="tab_content">
	<p id="notice"><div id="edit_site_list" class="edit_site_list">
	<%= render :partial => 'edit_site_list', :locals => { :sites_forest => @sites_forest, :missing_in_db => @missing_in_db, :extra_in_db => @extra_in_db, :parent_div => 'edit_site_list', :inaccessible_sites => @inaccessible_sites } %>
</div>
</div>
<div class="admin">
<% if user_signed_in? %>
	<%= link_to "Manage genres", genres_path %> | <%= link_to "Manage disciplines", disciplines_path %> | <%= link_to "Manage archives", archives_path %> | <%= link_to "Manage federations", federations_path %> | <%= link_to "Manage white list", white_lists_path %> | <%= link_to "Log out", destroy_user_session_path, :method=>'delete' %>
<% else %>
<%= link_to "admin", new_user_session_path %>
<% end %>
</div>