Sites/collex/config/routes.rb
Collex::Application.routes.draw do

	get "/wrapper" => "home#wrapper"
  get "/login_slider" => "home#login_slider"

	get "test_js/general_dialog"

	match '/search/list_name_facet_all' => 'search#list_name_facet_all'
	post '/search/remember_resource_toggle' => 'search#remember_resource_toggle'
	match '/search/saved' => 'search#saved'
	match '/search/save_search' => 'search#save_search'
	post '/search/remove_saved_search' => 'search#remove_saved_search'
	match '/search/browse' => 'search#browse'
	match 'browse/saved/:username/:name' => 'search#saved_permalink'
	get '/search' => 'search#index'

	post '/search/auto_complete_for_q' => 'search#auto_complete_for_q'
	post '/search/auto_complete_for_search_university' => 'search#auto_complete_for_search_university'

	post '/results/get_annotation' => 'results#get_annotation'
	post '/results/get_annotation_feedback' => 'results#get_annotation_feedback'
	post '/results/add_object_to_exhibit' => 'results#add_object_to_exhibit'
	post '/results/add_tag' => 'results#add_tag'
	post '/results/bulk_add_tag' => 'results#bulk_add_tag'
	post '/results/bulk_collect' => 'results#bulk_collect'
	post '/results/bulk_uncollect' => 'results#bulk_uncollect'
	post '/results/collect' => 'results#collect'
	post '/results/edit_tag' => 'results#edit_tag'
	match '/results/redraw_result_row_for_popup_buttons' => 'results#redraw_result_row_for_popup_buttons'
	post '/results/remove_all_tags' => 'results#remove_all_tags'
	post '/results/remove_tag' => 'results#remove_tag'
	post '/results/set_annotation' => 'results#set_annotation'
	post '/results/uncollect' => 'results#uncollect'
	post '/results/resend_exhibited_objects' => 'results#resend_exhibited_objects'

	match '/help/resources' => 'help#resources'
	match '/help/sites' => 'help#sites'

	post '/communities/view_by' => 'communities#view_by'
	post '/communities/sort_by' => 'communities#sort_by'
	post '/communities/search' => 'communities#search'
	post "/communities/page" => "communities#page"

	post '/builder/add_additional_author' => 'builder#add_additional_author'
	post '/builder/change_exhibits_group' => 'builder#change_exhibits_group'
	post '/builder/change_exhibits_cluster' => 'builder#change_exhibits_cluster'
	post '/builder/change_sharing' => 'builder#change_sharing'
	post '/builder/change_img_width' => 'builder#change_img_width'
	post '/builder/change_element_type' => 'builder#change_element_type'
	get '/builder/change_page' => 'builder#change_page'
	post '/builder/edit_exhibit_overview' => 'builder#edit_exhibit_overview'
	post '/builder/edit_text' => 'builder#edit_text'
	post '/builder/edit_header' => 'builder#edit_header'
	post '/builder/edit_element' => 'builder#edit_element'
	post '/builder/edit_illustration' => 'builder#edit_illustration'
	post '/builder/find_page_containing_element' => 'builder#find_page_containing_element'
	post '/builder/get_all_collected_objects' => 'builder#get_all_collected_objects'
	post '/builder/get_alias_users' => 'builder#get_alias_users'
	post '/builder/modify_outline' => 'builder#modify_outline'
	post '/builder/modify_outline_page' => 'builder#modify_outline_page'
	post '/builder/modify_border' => 'builder#modify_border'
	post '/builder/remove_additional_author' => 'builder#remove_additional_author'
	post '/builder/remove_exhibited_object' => 'builder#remove_exhibited_object'
	post '/builder/redraw_exhibit_page' => 'builder#redraw_exhibit_page'
	post '/builder/refresh_outline' => 'builder#refresh_outline'
	post '/builder/reset_exhibit_page_from_outline' => 'builder#reset_exhibit_page_from_outline'
	post '/builder/set_exhibit_author_alias' => 'builder#set_exhibit_author_alias'
	post '/builder/publish_exhibit' => 'builder#publish_exhibit'
	post '/builder/update_fonts' => 'builder#update_fonts'
	post '/builder/update_objects_in_exhibits' => 'builder#update_objects_in_exhibits'
	post '/builder/update_title' => 'builder#update_title'
	post '/builder/verify_title' => 'builder#verify_title'
	post '/builder/change_illustration_justification'
	post '/builder/insert_illustration'
	post '/builder/edit_row_of_illustrations'
	post '/builder/import_exhibit'
	post '/builder/modify_outline_add_first_element'

	config_file = File.join(Rails.root, "config", "site.yml")
	my_collex = 'my_collex'
	plugins = {}
	if File.exists?(config_file)
		site_specific = YAML.load_file(config_file)
		my_collex = site_specific['my_collex_url']
		plugins = site_specific['plugins'] || {}
		plugins.delete_if { |key, value| value != true }
	end
	get "/#{my_collex}" => 'my_collex#index'
	get "/#{my_collex}/results" => 'my_collex#results'
	get "/#{my_collex}/get_typewright_documents" => 'my_collex#get_typewright_documents'
	post "/#{my_collex}/results" => 'my_collex#results'

	post '/my_collex/remove_profile_picture' => 'my_collex#remove_profile_picture'
	post '/my_collex/show_profile' => 'my_collex#show_profile'
	post '/my_collex/update_profile_upload' => 'my_collex#update_profile_upload'
	post '/my_collex/update_profile' => 'my_collex#update_profile'

	if plugins['typewright']
		get "typewright/edit"
		post "typewright/remove_doc"

		namespace :typewright do
			get 'documents/not_available'
			get 'documents/not_signed_in'
			post 'documents/instructions'
			post 'documents/:id/complete' => 'documents#page_complete'
			post 'documents/:id/status' => 'documents#update_status'
			post 'documents/:id/report' => 'documents#report'
      put 'documents/:id/delete_edits' => 'documents#delete_edits'
			resources :admin do
				collection do
					get 'stats'
				end
			end
			resources :documents
			resources :lines
			resources :document_users
			resources :overviews, only: [ :index, :show ] do
				collection do
					get 'retrieve_doc'
				end
			end
		end

    get "typewright" => 'typewright/documents#index'

	end

	get "/login/logout" => "login#logout"
	post "/login/verify_login" => "login#verify_login"
	post "/login/submit_signup" => "login#submit_signup"
	post "/login/recover_username" => "login#recover_username"
	post "/login/reset_password" => "login#reset_password"
	get "/login/login_controls" => "login#login_controls"

	match "/forum/view_thread" => "forum#view_thread"
	match "/forum/view_topic" => "forum#view_topic"
	match "/forum/get_nines_obj_list_with_image" => "forum#get_nines_obj_list_with_image"
	match "/forum/get_exhibit_list" => "forum#get_exhibit_list"
	match "/forum/get_nines_obj_list" => "forum#get_nines_obj_list"
	post "/forum/post_comment_to_existing_thread" => "forum#post_comment_to_existing_thread"
	match "/forum/result_count" => "forum#result_count"
	post "/forum/edit_existing_comment" => "forum#edit_existing_comment"
	post "/forum/delete_comment" => "forum#delete_comment"
	post "/forum/post_comment_to_new_thread" => "forum#post_comment_to_new_thread"
	match "/forum/get_all_topics" => "forum#get_all_topics"
	post "/forum/post_object_to_new_thread" => "forum#post_object_to_new_thread"
	post "/forum/report_comment" => "forum#report_comment"
	post '/forum/get_object_details' => 'forum#get_object_details'

	post "/classroom/facet_on_group" => "classroom#facet_on_group"
	post "/classroom/search" => "classroom#search"
	post "/classroom/sort_by" => "classroom#sort_by"
	post "/classroom/view_by" => "classroom#view_by"
	post "/classroom/page" => "classroom#page"

	post "/groups/remove_profile_picture/:id" => "groups#remove_profile_picture"
	get '/groups/stale_request' => 'groups#stale_request', :as => :stale_request
	get '/groups/accept_request' => 'groups#accept_request', :as => :accept_request
	get '/groups/decline_request' => 'groups#decline_request', :as => :decline_request
	match '/groups/decline_invitation' => 'groups#decline_invitation', :as => :decline_invitation
	match '/groups/accept_invitation' => 'groups#accept_invitation', :as => :accept_invitation
	get '/groups/acknowledge_notification' => 'groups#acknowledge_notification', :as => :acknowledge_notification
	match '/groups/create_login' => 'groups#create_login', :as => :create_login
	match 'groups/create_login_create' => 'groups#create_login_create'
	get '/groups/:group/:cluster' => 'clusters#show'
	post "/groups/limit_exhibit" => "groups#limit_exhibit"
	post "/groups/unlimit_exhibit" => "groups#unlimit_exhibit"
	post "/groups/sort_exhibits" => "groups#sort_exhibits"
	post "/groups/unpublish_exhibit" => "groups#unpublish_exhibit"
	post "/groups/group_exhibits_list" => "groups#group_exhibits_list"
	post "/groups/notifications" => "groups#notifications"
	post "/groups/edit_membership" => "groups#edit_membership"
	post "/groups/render_license" => "groups#render_license"
	post "/groups/check_url" => "groups#check_url"
	post "/groups/edit_thumbnail" => "groups#edit_thumbnail"
	post "/groups/sort_cluster" => "groups#sort_cluster"
	post "/groups/leave_group" => "groups#leave_group"
	post "/groups/request_join" => "groups#request_join"
	post "/groups/verify_group_title" => "groups#verify_group_title"
	post '/groups/get_all_groups' => 'groups#get_all_groups'
	post '/groups/accept_as_peer_reviewed' => 'groups#accept_as_peer_reviewed'
	post '/groups/reject_as_peer_reviewed' => 'groups#reject_as_peer_reviewed'
	post '/groups/pending_requests' => 'groups#pending_requests'

	post "/clusters/remove_profile_picture" => "clusters#remove_profile_picture"
	post "/clusters/move_exhibit" => "clusters#move_exhibit"
	post "/clusters/edit_thumbnail" => "clusters#edit_thumbnail"
	post "/clusters/check_url" => "clusters#check_url"

	post "/admin/default/refresh_cached_objects" => "admin/default#refresh_cached_objects"
	get "/admin/facet_tree/index" => "admin/facet_tree#index"
	get "/admin/features/index" => "admin/features#index"
	get "/admin/user_roles/index" => "admin/user_roles#index"
	get "/admin/discussion_topics/index" => "admin/discussion_topics#index"
	get "/admin/default/forum_pending_reports" => "admin/default#forum_pending_reports"
	get "/admin/default/stats" => "admin/default#stats"
	get "/admin/default/groups" => "admin/default#groups"

Sites/collex/app/helpers/my_collex_helper.rb
##########################################################################
# Copyright 2009 Applied Research in Patacriticism and the University of Virginia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################

module MyCollexHelper
  def down_char
    raw("&darr;")
  end
  def up_char
    raw("&uarr;")
  end
  def del_char
    raw("&times;")
  end
  def ins_char
    raw("&crarr;")
  end
  def change_char
    raw("&Delta;")
  end
  def left_char
    raw("&larr;")
  end
  def right_char
    raw("&rarr;")
  end
  def element_bullet
    raw("&para;")
  end
  def opened_char
    raw('&#x25BC;')
  end
  def closed_char
    raw('&#x25B2;')
  end
  
  def element_text_thumbnail(text)
    if text == nil || text.length == 0
      return "[no text]"
    end
    
    text = strip_tags(text)
    if text.length < 30
      return text
    else
      return text[0..29] + "..."
    end
  end
  
  def element_pic_thumbnail(element, pos)
    illustrations = element.exhibit_illustrations
    if illustrations.length > pos
      element_pic_thumbnail_illustration(illustrations[pos])
    else
      raw("<img src='#{get_image_url(nil)}' height='16px' />")
    end
  end
  
  def get_image_url(url)
    if url == nil || url.length == 0
      return image_path(DEFAULT_THUMBNAIL_IMAGE_PATH)
    end
    return url
  end

	def get_url_for_internal_image(image, ty = nil)
		# image is the item in the database that points to the image.
		# ty is :micro, :smaller, :thumb
		return "" if image == nil
		return "" if image.photo.url == nil
		return "/#{image.photo.url(ty)}" if ty
		return "/#{image.photo.url()}"
	end

  def element_pic_thumbnail_illustration(illustration)
    if illustration.illustration_type == ExhibitIllustration.get_illustration_type_image()
      raw("<img src='#{get_image_url(illustration.image_url)}' height='16px' />")
    elsif illustration.illustration_type == ExhibitIllustration.get_illustration_type_nines_obj()
      thumb = CachedResource.get_thumbnail_from_uri(illustration.nines_object_uri)
      raw("<img src='#{get_image_url(thumb)}' height='16px' />")
    elsif illustration.illustration_type == ExhibitIllustration.get_illustration_type_text()
      "..."
    end
  end

  def tree_node( page_num, item_id_prefix, class_name, toggle_function, exhibit_id, num_pages, initial_state )
    display_none = 'style="display:none"'
    label = ""
    if num_pages > 1  # We don't want any page controls if there is only one page.
      label << "<div class='outline_right_controls'>\n"
      if page_num.to_i > 1
        label << link_to_function(up_char(), "doAjaxLinkOnPage('move_page_up', #{exhibit_id}, #{page_num} );", { :title => 'Move Page Up', :class => 'modify_link' }) + "\n"
      end
      if page_num.to_i < num_pages
        label << link_to_function(down_char(), "doAjaxLinkOnPage('move_page_down', #{exhibit_id}, #{page_num} );", { :title => 'Move Page Down', :class => 'modify_link' }) +"\n"
      end
      label << '&nbsp;<span class="close_link">'
      label << link_to_function(del_char(), "doAjaxLinkOnPage('delete_page', #{exhibit_id}, #{page_num} );", { :title => 'Delete Page', :class => 'modify_link' })
      label << "</span>\n"
      label << "</div>\n"
    end
    
    label << "<span id=\"#{item_id_prefix}_p#{page_num}_closed\" #{initial_state == :open ? display_none : ''} >"
    label << link_to_function(closed_char(),"#{toggle_function}('#{item_id_prefix}_p#{page_num}')", { :class => 'modify_link' })
    label << "</span>\n"
    label << "<span id=\"#{item_id_prefix}_p#{page_num}_opened\" #{initial_state == :closed ? display_none : ''} >"
    label << link_to_function(opened_char(), "#{toggle_function}('#{item_id_prefix}_p#{page_num}')", { :class => 'modify_link'})
    label << "</span>\n"
    label << "<span class='#{class_name}'>" + "Page " + page_num + "</span>\n"
	return raw(label)
  end  
  
  def create_border_div(element, border_active, border_class)
    # This creates either an open div tag with a border, nothing, or a close div tag .
    # If this is the first element in a section, then is_first is returned true .
    close_div = "</div>\n"
    open_div = "<div class='#{border_class}'>\n"
    border_type = element.get_border_type()
    if border_type == "start_border" && border_active == true
      html = close_div + open_div
      border_active = true
      #is_first = true
    elsif border_type == "start_border" && border_active == false
      html = open_div
      border_active = true
      #is_first = true
    elsif border_type == "continue_border" && border_active == true
      html = ""
      border_active = true
      #is_first = false
    elsif border_type == "continue_border" && border_active == false
      html = open_div
      border_active = true
      #is_first = true
    elsif border_type == "no_border" && border_active == true
      html = close_div
      border_active = false
      #is_first = true
    elsif border_type == "no_border" && border_active == false
      html = ""
      border_active = false
      #is_first = true
    end
    
    return { :border_active => border_active, :html => raw(html) }
  end

	def exhibit_builder_style_name(exhibit)
		if exhibit.fonts_match_defaults()
			return "#{Setup.site_name()} default"
		else
			return "Custom style"
		end
	end
end

Sites/collex/app/views/my_collex/_login_instructions.html.erb
<% #
    # ------------------------------------------------------------------------
    # Copyright 2009 Applied Research in Patacriticism and the University of Virginia
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #    http://www.apache.org/licenses/LICENSE-2.0

    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # ---------------------------------------------------------------------------- -%>

<div class="my_collex_instructions">
	<%= image_tag(GENERIC_USER_IMAGE_PATH, { alt: 'Generic user'}) %>
	<h2>You are not logged in.</h2>
	<p><%= sign_in_link({ :class => 'nav_link', :text => 'Log in' }) %> or <%= sign_up_link({ :class => 'nav_link', :text => 'create an account' }) %> to collect and tag items, save and share searches, create exhibits, and set up your profile.</p>
    <%= image_tag("#{SKIN}/join_my_collex.gif", { alt: 'explanation of benefits'}) %>
	<div class="clear_both"></div>
</div>

Sites/collex/app/views/my_collex/_my_discussions_list.html.erb
<% # 
    # ------------------------------------------------------------------------
    # Copyright 2009 Applied Research in Patacriticism and the University of Virginia
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #    http://www.apache.org/licenses/LICENSE-2.0
  
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # ---------------------------------------------------------------------------- -%>
<%# my_discussions_list : parameters: user_id -%>
<div class="right_column_header">My Discussions</div>
<% my_comments = DiscussionComment.where({user_id: user_id}) -%>
<% my_threads = {} -%>
<% my_comments.each { |comment| -%>
	<% my_threads[comment.discussion_thread_id] = true -%>
<% } -%>
<% if my_threads.length == 0 -%>
	<div class="empty_list_text" >You have not started or joined any discussions</div>
<% else -%>
	<ul class="my_discussions">
		<% for thread_id in my_threads -%>
			<% thread = DiscussionThread.find_by_id(thread_id[0]) -%>
			<% if thread != nil # this should always be true, but if the database gets a little corrupted, but don't want to crash -%>
				<li><%= link_to(thread.get_title(), { :controller => 'forum', :action => 'view_thread', :thread => thread_id[0] }, :class => 'nav_link') %>&nbsp;<%= image_tag("#{SKIN}/notice_thumb.gif", :height => '16', :alt => 'Recent Activity') if !DiscussionVisit.user_has_seen_all_comments(user_id, thread) %></li>
			<% end -%>
		<% end -%>
	</ul>
<% end -%>

Sites/collex/app/views/my_collex/_my_exhibits_list.html.erb
<% # 
    # ------------------------------------------------------------------------
    # Copyright 2009 Applied Research in Patacriticism and the University of Virginia
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #    http://www.apache.org/licenses/LICENSE-2.0
  
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # ---------------------------------------------------------------------------- -%>
<%# my_exhibits_list params: int user_id -%>
<div class="right_column_header">My Exhibits</div>
<div class="new_exhibit_link"><%= link_to_function "Create New Exhibit", "var dlg = new CreateNewExhibitWizard({ progress_img: '#{image_path(PROGRESS_SPINNER_PATH)}', import_url: '/builder/import_exhibit', url_get_objects: '/builder/get_all_collected_objects', populate_collex_obj_url: '/forum/get_nines_obj_list_with_image'}); dlg.show();", :class => 'modify_link' %>
</div>
<% my_exhibits = Exhibit.where("user_id = ? OR alias_id = ?", user_id, user_id) -%>
<% if my_exhibits.length == 0 -%>
	<div class="empty_list_text" >You have not created any exhibits</div>
<% else -%>
	<% for exhibit in my_exhibits -%>
		<div class="side_bar_exhibit_thumbnail"><%= render :partial => 'exhibits/exhibit_thumbnail', :locals => { :exhibit => exhibit, :show_immediately => false } %></div>
		<div class="side_bar_exhibit_text exhibit_link"><%= exhibit.title %> <a class="nav_link" href="/exhibits/view/<%= exhibit.id %>">[view]</a> 
			<% if Exhibit.can_edit(current_user, exhibit.id) -%>
			<%= link_to "[edit]", { :controller => 'builder', :action => 'show', :id => exhibit.id }, { :class => 'nav_link' } %>
			<% else -%>
			<div>Peer Reviewed</div>
			<% end -%>
		</div>
		<div class="side_bar_exhibit_spacer clear_both"></div>
	<% end -%>
<% end # if there are exhibits -%>

Sites/collex/app/views/my_collex/_my_groups_list.html.erb
<% # 
    # ------------------------------------------------------------------------
    # Copyright 2009 Applied Research in Patacriticism and the University of Virginia
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #    http://www.apache.org/licenses/LICENSE-2.0
  
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # ---------------------------------------------------------------------------- -%>
<%# my_groups_list : parameters: user_id -%>
<div class="right_column_header">My Groups</div>
<% my_groups = Group.get_all_users_groups(user_id) -%>
<% if my_groups.length == 0 -%>
	<div class="empty_list_text" >You have not started or joined any groups.</div>
<% else -%>
<% for group in my_groups -%>
	<div class="side_bar_exhibit_thumbnail"><%= render :partial => 'common/thumbnail', :locals => { :element_id => "group_#{group.id}", :url => get_group_image_url(group), :show_immediately => false } %></div>
	<div class="side_bar_exhibit_text exhibit_link"><%= link_to(group.name, { :controller => 'groups', :action => 'show', :id => group.get_visible_id() }, { :class => 'nav_link' }) %>
		<% if group.is_editor(user_id) %>
	        <%= image_tag("group_admin.png", { title: 'administrator', alt: 'administrator', class: "group_admin_img" }) %>
		<% end%>
	</div>
	<div class="side_bar_exhibit_spacer clear_both"></div>
<% end -%>
<% end -%>
<div class="create-group-links">
	<%= link_to_function("Create Group", "new CreateGroupWizardDlg('/search/auto_complete_for_search_university', '#{user_id}', '/groups/verify_group_title', '/groups', '/groups/', #{Group.types_to_json(true)}, #{Group.permissions_to_json()}, #{Group.visibility_to_json()}, '#{Group.types()[0]}', '#{Setup.site_name()}', '/forum/get_nines_obj_list', '#{image_path(PROGRESS_SPINNER_PATH)}', '#{User.find(user_id).institution}', '#{User.find(user_id).fullname}', '#{image_path("#{SKIN}/new_group_show_membership_example.jpg")}'); return false;", :class => 'nav_link' ) %>
	<%= link_to_function("[Browse Groups]", "new BrowseGroupsDlg('#{image_path(PROGRESS_SPINNER_PATH)}', '/groups/get_all_groups', 'browse_groups'); return false;", { :class => 'nav_link' }) %>
</div>

Sites/collex/app/views/my_collex/_profile.html.erb
<% # 
    # ------------------------------------------------------------------------
    # Copyright 2009 Applied Research in Patacriticism and the University of Virginia
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #    http://www.apache.org/licenses/LICENSE-2.0
  
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # ---------------------------------------------------------------------------- -%>
<%# profile: params: ActiveRecord user, bool can_edit -%>
<div class="profile_image">
	<%= image_tag(get_user_picture(user.id, :full), :class => 'profile_image') %>
<% if can_edit && user.image -%>
	<br /><div class="profile_remove_picture"><%= link_to "Remove Picture", "/my_collex/remove_profile_picture", { :id => 'remove_picture', :method => 'post' } %></div>
	<script type="text/javascript">
		var createRemovePictureButton = function() {
			var onButtonClick = function (e) {
				postLink($("remove_picture-button").href);
			};


			new YAHOO.widget.Button('remove_picture', { onclick: { fn: onButtonClick } });
			YAHOO.util.Event.onAvailable('remove_picture-button', function() {
				$('remove_picture-button').writeAttribute('onclick', 'return false;');	// This keeps the '#' out of the address bar
			}, this);
		};
		document.observe('dom:loaded', function() {
			createRemovePictureButton();
		});
		try {
			createRemovePictureButton();
		} catch(e) {};
	</script>
<% end -%>
</div>
<% if can_edit -%>
	<div class="profile_edit"><%= link_to_function "Edit Profile", "new EditProfileDialog('profile', '/my_collex/update_profile', #{user.to_json()}, '#{get_user_picture(user.id, :full)}');", :class => 'nav_link' %></div>
<% end -%>
<div class="profile_div"><span class="profile_label">Username:</span><span><%= user.username %></span><span>&nbsp;</span></div>
<div class="profile_div"><span class="profile_label">Full name:</span><span><%= user.fullname %></span><span>&nbsp;</span></div>
<% if can_edit || user.hide_email != 'true' %>
<div class="profile_div"><span class="profile_label">Email:</span><span><%= user.email %></span><span>&nbsp;</span></div>
<% end %>
<% if can_edit %>
<div class="profile_div"><span class="profile_label">&nbsp;</span><span><%= user.hide_email == 'true' ? '(Email address is hidden from other users)' : '(Email address is visible)' %></span><span>&nbsp;</span></div>
<% end %>
<div class="profile_div"><span class="profile_label">Institution:</span><span><%= user.institution %></span><span>&nbsp;</span></div>
<div class="profile_div"><span class="profile_label">Link:</span><span><%= user.link != nil && user.link.length > 0 ? make_ext_link(user.link) : "" %></span><span>&nbsp;</span></div>
<div class="profile_div">
	<span class="profile_label">About me:</span>
	
	<% if !user.about_me.nil? && user.about_me.length > 0 %>
		<span class="profile_paragraph"><%= user.about_me %></span>
	<%else%>
        <%if can_edit %>
            <span class="profile_hint">You have not entered any information about yourself. Click
                <%= link_to_function "here", "new EditProfileDialog('profile', '/my_collex/update_profile', #{user.to_json()}, '#{get_user_picture(user.id, :full)}');", :class => 'nav_link' %>
                 to add a brief description.</span>
        <%end%>
	<%end%>
	
	<span>&nbsp;</span>
</div>